# Generated by Django 5.1.6 on 2025-02-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naatvideo',
            name='tags',
            field=models.TextField(blank=True, default='', help_text='Comma-separated tags', null=True),
        ),
    ]
